### ISSUE TITLE
from m2convertor import 

### ISSUE THREAD

**Issue by mavislily0219** [JamyDon/PLM-based-CGEC-Model-Ensemble#2]
您好，我在MuCGEC的m2convertor代码中没有找到edit-combination.py中的引用from m2convertor import generate_tgt 请问这个该在哪里找

**Comment by JamyDon** [comment]
您好，感谢您提出的问题。现已更新代码，将 `generate_tgt` 添加到了 `utils.py` ，同时引用的 `m2convertor` 改为了 `utils`。使用最新版本的代码即可。

很抱歉此前的疏忽使您困扰。

**Comment by mavislily0219** [comment]
非常感谢！
